[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 600, height = 600, color = [150, 150, 200, 255] }

    [entity.components.Transform]
    translation = { x = 300.0, y = 300.0 }
    depth = 0.0
